### ISSUE TITLE
Notes Date/Time Last Modified

### ISSUE THREAD

**Issue by binary1985** [lair-framework/lair#100]
It would be nice if we had an indicator such as a Date/Time stamp of when a note was last updated. When working collaboratively on a multiday gig, its nice to have a quick overview of what the other tester may have changed. If date/time is annoying to do, I think a "New Updates Flag Since Last Viewed" or something would work, kinda like "You got mail!"

**Comment by ilyaglow** [comment]
What you think about something like [collection hooks](https://github.com/matb33/meteor-collection-hooks)? Actually resolving this issue could be a part of something bigger that honestly I dream about - a simple dashboard with some kind of timelog. As a user I'd like to be aware of who or what tool added/changed what to track new data and avoid doing the same things twice. The feature at `projects/:projectid/settings/log` helps a bit, but it doesn't give you straight connection between `command` object and `droneLog` string, not to mention changes done by user.

**Comment by tomsteele** [comment]
I have some big concerns about performance... Where we already struggle with large data sets. Future versions of lair will be moving to Postgres where we can easily bake this in.
