### ISSUE TITLE
Heroku Admin Password.

### ISSUE THREAD

**Issue by 0day1day** [lair-framework/lair#105]
Hey folks after Heroku autoinstall, what's the password to access? i can't see the mongo log to see the password. Or is there anyway way to reset?

**Comment by ilyaglow** [comment]
Hey, the password should be in the app logs. It is generated on the first Lair run and printed out: https://dashboard.heroku.com/apps/LAIR-APP-NAME/logs

Search for the “Created admin@localhost with password”

Old logs might be truncated by heroku so the only option if your instance is pretty old is to connect to your generated mongolab db instance (Reveal Config Vars on https://dashboard.heroku.com/apps/LAIR-APP-NAME/settings) and change admin's bcrypted password to a chosen one.

**Comment by 0day1day** [comment]
thanks @ilyaglow i create new instance and password appears in the logs.

Cheers!
