### ISSUE TITLE
[UI/Functionality] Keyboard shortcuts (both sitewide where appropriate and specific on individual pages)

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#36]
Being able to use keyboard shortcuts to navigate the features of the site, as well as specific functions on each page would increase usability/efficiency.

I envision this to work something like keyboard shortcuts on Github/GMail/etc

Could support vim style shortcuts as well as other custom ones?

Eg. 
* ? -> Show the available keyboard shortcuts
* s or / for search -> Focus the search box so that additional text typed applies to it.
* etc

**Comment by tomsteele** [comment]
This is now in 2.0.0 branch
