### ISSUE TITLE
[Scripts] Menu option/page (similar to notes) for storing scripts + sitewide ability to run them

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#37]
The current notes/developer console option is a good interim solution, but I think going forward it would be useful to have a seperate 'scripts' page.

This would allow you to save scripts (as you currently can with notes), but also specify the page/pages/etc where they can be run.

This would be coupled with a sitewide option to execute scripts on the current page (could be a button/dialog, dropdown showing avaialble scripts for the current context, keyboard shortcut #36 , etc)

This could also implement either a link, or a direct ability to load scripts from the [Lair Browser Scripts](https://github.com/fishnetsecurity/Lair-Browser-Scripts) repo (or alternatively allow adding your own personal repo/sources as well)

**Comment by tomsteele** [comment]
Going to close this, it would be awesome for someone to implement a solution outside of this repo as a general tool. But I don't want to build this into Lair directly as it would just be a messy hack, even messier than executing javascript in the console :P
