### ISSUE TITLE
[Hosts] Button to go back from host details to hosts list (and remember scroll position)

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#41]
This would in essence be a 'back button' (instead of having to click back through the main menu.

It would be very useful if this would remember/persist options from the page before (eg. scroll position (anchor link to hostname we came from?), hosts displayed (#'s of, all, etc)

**Comment by tomsteele** [comment]
I don't think this is needed, we don't have that much of deep linking, it's 1 click to get back to where you were. Going to close this for now.
