### ISSUE TITLE
[Hosts] Host summary onhover of IP address

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#42]
This would be a convenience/UI enhancement to display an onhover dialog box with a summary of the details for a host.

I would think this should have a expandable headings for each main tab (services, vulnerabilities, operating systems, notes, hostnames, credentials)

These would show a number after them (eg. [+] Services (13)), and would be collapsed by default.

Any information/details that doesn't need to be collapsed would be shown as a string above the expandable headings.

An alternative to showing all this information onhover of the IP address would be to show it onhover for each particular cell/column. (Eg. hovering over the hostname for a particular entry would show the weighted list of all hostnames (and allow you to change the weighting/add new/etc?)

**Comment by tomsteele** [comment]
We've decided not to pursue this as the performance impact would be too high, and we have views to view the useful data quicker. If someone submits a PR and it performs well when we have a ton of hosts we'll accept it.
