### ISSUE TITLE
[Notes] Ability to associate 'global' notes to a particular port/service/etc

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#43]
This would allow you to associate a global note attached to a particular service/port/ combination, etc. This would show up for that service/port wherever it appears (on all hosts, etc)

Ideally, these global notes would be able to persist between projects.

I see this as being an easy way to provide helpful notes/knowledge base (eg. tools to use for further investigation of that service, command line options, notes of things to remember/investigate further, etc) This would enhance the information sharing aspects, especially allowing newer/less experienced team members to benefit more from the wisdom of those more experienced testers.

**Comment by tomsteele** [comment]
I've decided against this. I'm going to work on a project separate from this, and we'll build a drone to integrate and aggregate the data.
