### ISSUE TITLE
[Services] Color and link to hosts on right hand side

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#44]
I'm not sure that colouring can be changed on an individual line as it's currently implemented (and changing it from a textfield would lose the ability to ctrl-a)

I'm thinking the addition of 2 icons to the left/right of each line of the ip address list.
* The first would show the current color for that host, and clicking on it would change the color.
* The second would allow linking through to the associated host entry.

It may also be beneficial to provide an onhover option (3rd icon?) giving a summary of the host. This could use the same code that would be required by #42

**Comment by tomsteele** [comment]
No action on this issue in a long time. We're changing the UI quite a bit, so let's revisit if this is still an issue in the next version.
