### ISSUE TITLE
Using Lair without internet connectivity

### ISSUE THREAD

**Issue by 5k3pt1c** [lair-framework/lair#62]
Lair pulls a font from an external site. When used in a closed network the font cannot be loaded. This causes various buttons and flags to not load. Among the affected buttons and flags are the Vulnerability flags and buttons for expanding chat. If the font were loaded internally it would fix the usability issue for those conducting tests within closed networks.

**Comment by tomsteele** [comment]
Yep, need to fix this.

**Comment by tomsteele** [comment]
Fixed in 1.1.0
