### ISSUE TITLE
Add a "New/Assign Issue" Button to the Host view.

### ISSUE THREAD

**Issue by JamHaven** [lair-framework/lair#82]
It would be very handy, to implement a "New Issue" or "Assign Issue" Button to the Host view.
At the momen you have to create Issus in the root view to assign hosts to them. But sometimes you want to take a closer look at a host and add, or assign issues to them.

**Comment by tomsteele** [comment]
Sounds like a good enhancement. @mattlowe, something you could implement?

**Comment by tomsteele** [comment]
@JamHaven Added with https://github.com/lair-framework/lair/commit/af1ee9e1ca6fb17d63e62aa6b1a2f9a4c755450b
