### ISSUE TITLE
Screenshot upload doesn't seem to work

### ISSUE THREAD

**Issue by timogoosen** [lair-framework/lair#84]
I've tried uploading screenshots, but it doesn't seem to work.
I've tried looking at the logs etc, but nothing works.
I've tried reinstalling lair etc, but not working.

Any ideas of what to do? Maybe this is an old issue?

**Comment by tomsteele** [comment]
@timogoosen I would imagine you don't have the API server running. Can you show me your output of `sudo netstat -plnt` (I'm assuming Linux). Can you confirm that you are using caddy to proxy all requests through a single port? Screenshot uploading will not work unless you are accessing Lair over the HTTPS service started from caddy, as it uses the API server for these requests. You can try inspecting the request in Chrome/Firefox debugger as well.

**Comment by timogoosen** [comment]
Um I'll look into it.
Do you guys have a developer guide somewhere that explains all the different components and setting up the dev environment?

**Comment by tomsteele** [comment]
@timogoosen no, we don't at the moment. I can write something up, but you'll have to give me a few days to get it done. In the meantime, what did you want to work on? Maybe I can give you some help.

**Comment by timogoosen** [comment]
I'm not very familiar with nodejs, more familiar with python and django, but I wanted to see if I can change lair framework a bit for web app hacking for example to have a view where you can view by subdomain or even by vhost. At the moment everything is by IP and sometimes it is useful to create an issue only for a certain vhost or subdomain. Hope that makes sense?

**Comment by tomsteele** [comment]
@timogoosen That makes sense, and is something I have put a lot of thought into. However, I don't personally find Lair to be all that useful when doing an Application specific penetration test. I do find it useful when attacking an entire organization/environment, and in those environments contain applications, so you are right on, sometimes it's better to express application bugs to a vhost/subdomain. I completely agree.

In the end, this is something I could see for a Lair 3. Now, you would probably be able to do that yourself rather easily. But, you will need to get familiar with https://www.meteor.com/. Which is the main server/client component of lair, and this repo. However, if you start adding things to the database schema, you would probably want to update the JSON API https://github.com/lair-framework/api-server as well.
