### ISSUE TITLE
Replace .node_version.txt with .nvmrc

### ISSUE THREAD

**Issue by alias1** [lair-framework/lair#86]
The installation instructions talk about using [nvm](https://github.com/creationix/nvm), yet the latest OSX release has a `.node_version.txt` file instead of a `.nvmrc`.

**Comment by tomsteele** [comment]
`.node_version.txt` is placed by Meteor as part of the build/bundle process. That file, or `.nvmrc` is not used by the install or run process at all. You can safely ignore them.
