### ISSUE TITLE
Update hosts information

### ISSUE THREAD

**Issue by X-C3LL** [lair-framework/lair#88]
Hi!

I am trying to use the API with pylair in order to modify host information but I don't see any example about how to do it. Is there a way to update/modify host information (for example statusMessages) using the API? and to delete hosts/services/etc ?

Thank you.

**Comment by tomsteele** [comment]
hi @X-C3LL. You essentially modify a dict and then call import project. Maybe this will help? https://github.com/lair-framework/drone-smbversion/blob/master/drone-smbversion.py

You can not currently delete hosts and services. Maybe checkout the browser scripts.
