### ISSUE TITLE
How do I import nexpose scan

### ISSUE THREAD

**Issue by rschwass** [lair-framework/lair#91]
I can not seem to find out how to import a nexpose scan in the documentation.
I am having trouble getting any of the go scripts to run, as Im a go newb.

**Comment by rschwass** [comment]
I get OsMatch error module has no method bla bla bla when I run go get github.com/lair-framework/drone-nmap aswell

**Comment by tomsteele** [comment]
Hi @rschwass, we https://github.com/lair-framework/drone-nexpose as a place holder for a nexpose drone. Unfortunately, none of us core contributors are active users of nexpose, thus it isn't supported at the moment.

We do have an XML parser for Go here: https://github.com/lair-framework/go-nexpose.

To write a nexpose drone, you would probably copy of a lot of the logic uses in the nessus drone https://github.com/lair-framework/drone-nessus/blob/master/main.go.

 To execute the drones, please read https://github.com/lair-framework/lair/wiki/Drone-Usage-(Getting-data-in-and-out-of-Lair). If you're having a problem getting them to run, I would suggest sticking to the compiled versions. For example, the Nmap drone has binaries for OS X, Linux, and Windows here https://github.com/lair-framework/drone-nmap/releases/tag/v2.1.1.

I'm going to close this issue, if you would like to paste the actual error you received, I might be able to help further. Good luck, and please let me know if you need anything else.
